name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Get Package
        run: sudo apt-get update && sudo apt-get install -y libsfml-dev
      - uses: actions/checkout@v2
      - name: make
        run: make
