name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Get Package
        uses: mstksg/get-package@v1
        with:
         apt-get: libsfml-dev
      - uses: actions/checkout@v2
      - name: make
        run: make
