name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0
      - uses: actions/checkout@v2
      - name: Set up conan
        run: >
          conan remote add epitech https://api.bintray.com/conan/epitech/public-conan &&
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan &&
          mkdir build &&
          cd build &&
          conan install .. --build=missing
      - name: build conan
        uses: ashutoshvarma/action-cmake-build@v1
