name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get Package
  # You may pin to the exact commit or the version.
  # uses: mstksg/get-package@4eda30bb5c6ac62c0f3921dd5884b6ef8fc89ab2
        uses: mstksg/get-package@v1
        with:
         apt-get: libsfml-dev
      - uses: actions/checkout@v2
      - name: make
        run: make
